/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export enum AdditionalFieldsV1 {
  "tracking_account_number" = "tracking_account_number",
  "tracking_postal_code" = "tracking_postal_code",
  "tracking_ship_date" = "tracking_ship_date",
  "tracking_key" = "tracking_key",
  "tracking_origin_country_region" = "tracking_origin_country_region",
  "tracking_destination_country_region" = "tracking_destination_country_region",
  "tracking_state" = "tracking_state",
}
