/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface CarbonEmissionsGetTrackingBySlugTrackingNumberResponse {
    /**
     * The unit in which the value field is expressed. Allowed values: kg
     */
    unit?: string;
    /**
     * The total amount of carbon emissions
     */
    value?: number;
}

