/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The source of the checkpoint, which can either be from the carrier or when the user marks the tracking as completed.
 */
export enum CheckpointSource {
  "carrier" = "carrier",
  "user" = "user",
}
