/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Describes the specific reason that led to the event.
 */
export interface CheckpointEventsReason {
  /**
   * The code of the reason.
   */
  code?: string;
}
