/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { CheckpointEventsReason } from "./CheckpointEventsReason";

/**
 *
 */
export interface CheckpointEvents {
  /**
   * Represents the event code.
   */
  code?: string;
  /**
   * Describes the specific reason that led to the event.
   */
  reason?: CheckpointEventsReason | null;
}
