/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The latitude and longitude coordinates indicate the precise location of the shipments that are currently in transit.
 */
export interface CheckpointCoordinate {
  /**
   * Represents the latitude.
   */
  latitude?: number;
  /**
   * Represents the longitude.
   */
  longitude?: number;
}
