/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface CoordinateCheckpoint {
    /**
     * Represents the latitude.
     */
    latitude?: number;
    /**
     * Represents the longitude.
     */
    longitude?: number;
}

