/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { CourierConnectionResponseForGetCourierConnectionsDataPagination } from "./CourierConnectionResponseForGetCourierConnectionsDataPagination";
import { CourierConnection } from "./CourierConnection";

/**
 *
 */
export interface CourierConnectionResponseForGetCourierConnectionsData {
  /**
   *
   */
  pagination?: CourierConnectionResponseForGetCourierConnectionsDataPagination;
  /**
   *
   */
  courier_connections?: CourierConnection[];
}
