/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { DataCourierResponse } from "./DataCourierResponse";

export interface CourierResponse {
    /**
     * Meta data
     */
    meta: Meta;
    /**
     * 
     */
    data: DataCourierResponse;
}

