/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { CourierResponseData } from "./CourierResponseData";

/**
 * Model of all couriers endpoint response
 */
export interface CourierResponse {
  /**
   * Meta data
   */
  meta: Meta;
  /**
   *
   */
  data: CourierResponseData;
}
