/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { DataCourierConnectionResponseForGetCourierConnections } from "./DataCourierConnectionResponseForGetCourierConnections";

export interface CourierConnectionResponseForGetCourierConnections {
    /**
     * Meta data
     */
    meta: Meta;
    /**
     * 
     */
    data?: DataCourierConnectionResponseForGetCourierConnections;
}

