/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { CourierConnectionResponseForGetCourierConnectionsData } from "./CourierConnectionResponseForGetCourierConnectionsData";

/**
 * Courier connection response for getting courier connections
 */
export interface CourierConnectionResponseForGetCourierConnections {
  /**
   * Meta data
   */
  meta: Meta;
  /**
   *
   */
  data?: CourierConnectionResponseForGetCourierConnectionsData;
}
