/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface Courier {
  /**
   * Unique code of courier. Get the slugs from .
   */
  slug?: string;
  /**
   * Name of courier
   */
  name?: string;
  /**
   * Contact phone number of courier
   */
  phone?: string;
  /**
   * Other name of courier
   */
  other_name?: string;
  /**
   * Website link of courier
   */
  web_url?: string;
  /**
   * The extra fields need for tracking, such as `tracking_account_number`, `tracking_postal_code`, `tracking_ship_date`, `tracking_key`, `tracking_destination_country_region`
   */
  required_fields?: string[];
  /**
   * The extra fields which are optional for tracking. Basically it&#39;s the same as required_fields, but the difference is that only some of the tracking numbers require these fields.
   */
  optional_fields?: string[];
  /**
   * Default language of tracking results
   */
  default_language?: string;
  /**
   * Other supported languages
   */
  support_languages?: string[];
  /**
   * Country/Region code (ISO Alpha-3) where the courier provides service
   */
  service_from_country_regions?: string[];
}
