/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { DataCourierResponseV1 } from "./DataCourierResponseV1";

export interface CourierResponseV1 {
  /**
   * Meta data
   */
  meta: MetaV1;
  /**
   *
   */
  data: DataCourierResponseV1;
}
