/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface CredentialField {
    /**
     * The display name of the credential field that users must provide when creating a carrier connection.
     */
    name?: string;
    /**
     * The data type of the credential field, indicating what kind of input is expected.
     */
    type?: string;
    /**
     * It indicates whether the credentials field must be provided or not when creating a carrier connection.
     */
    required?: boolean;
}

