/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface CustomersUpdateTrackingByIdRequest {
  /**
   * The  role of the customer, indicating whether the customer is  an individual or a company.
   */
  role?: string;
  /**
   * Customer name associated with the tracking.
   */
  name?: string;
  /**
   * The phone number(s) to receive SMS notifications. Phone numbers should begin with a `+` sign and include the area code.
   */
  phone_number?: string;
  /**
   * Email address(es) to receive email notifications.
   */
  email?: string;
  /**
   * The preferred language of the customer. If you have set up AfterShip notifications in different languages, we use this to send the tracking updates to the customer in their preferred language.
   */
  language?: string;
}
