/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PaginationDataTrackingResponseGetMultipleV1 } from "./PaginationDataTrackingResponseGetMultipleV1";
import { Tracking } from "./Tracking";

export interface DataTrackingResponseGetMultipleV1 {
    /**
     * The Pagination holds the information for the pagination when the response contains multiple objects.
     */
    pagination?: PaginationDataTrackingResponseGetMultipleV1;
    /**
     * Array of 
     */
    trackings?: Tracking[];
}

