/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PaginationDataCourierConnectionResponseForGetCourierConnections } from "./PaginationDataCourierConnectionResponseForGetCourierConnections";
import { CourierConnection } from "./CourierConnection";

export interface DataCourierConnectionResponseForGetCourierConnections {
    /**
     * 
     */
    pagination?: PaginationDataCourierConnectionResponseForGetCourierConnections;
    /**
     * 
     */
    courier_connections?: CourierConnection[];
}

