/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PaginationDataTrackingResponseForGetTrackings } from "./PaginationDataTrackingResponseForGetTrackings";
import { Tracking } from "./Tracking";

export interface DataTrackingResponseForGetTrackings {
    /**
     * The Pagination holds the information for the pagination when the response contains multiple objects.
     */
    pagination?: PaginationDataTrackingResponseForGetTrackings;
    /**
     * Array of 
     */
    trackings?: Tracking[];
}

