/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Notification } from "./Notification";

export interface DataNotificationResponseV1 {
    /**
     * Object describes the notification information.
     */
    notification?: Notification;
}

