/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PartialDeleteTracking } from "./PartialDeleteTracking";

export interface DataTrackingDeleteResponseV1 {
    /**
     * Partial tracking model
     */
    tracking?: PartialDeleteTracking;
}

