/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface DeleteCourierConnectionsByIdResponse {
    /**
     * The courier connection ID is a special set of numbers generated by AfterShip to define each user-created connection.
     */
    id?: string;
    /**
     * Unique courier code. Get courier codes .
     */
    courier_slug?: string;
    /**
     * It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
     */
    credentials?: {[key: string]: any};
    /**
     * The date and time the courier connection was created. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
     */
    created_at?: string;
    /**
     * The date and time the courier connection was updated. It uses the format YYYY-MM-DDTHH:mm:ssZ for the timezone GMT +0.
     */
    updated_at?: string;
}

