/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { SlugGroupV1 } from "./SlugGroupV1";

export interface DetectCourierRequest {
  /**
   * Tracking number of a shipment.
   */
  tracking_number: string;
  /**
   * If not specified, Aftership will automatically detect the courier based on the tracking number format and your . Use array to input a list of couriers for auto detect. Cannot be used with slug_group at the same time.
   */
  slug?: string[];
  /**
   * The postal code of receiver&#39;s address. Required by some couriers. Refer to  for more details
   */
  tracking_postal_code?: string;
  /**
   * Shipping date in `YYYYMMDD` format. Required by some couriers. Refer to  for more details
   */
  tracking_ship_date?: string;
  /**
   * Account number of the shipper for a specific courier. Required by some couriers. Refer to  for more details
   */
  tracking_account_number?: string;
  /**
   * Key of the shipment for a specific courier. Required by some couriers. Refer to  for more details
   */
  tracking_key?: string;
  /**
   * Origin Country/Region of the shipment for a specific courier. Required by some couriers.
   */
  tracking_origin_country_region?: string;
  /**
   * Destination Country/Region of the shipment for a specific courier. Required by some couriers. Refer to  for more details
   */
  tracking_destination_country_region?: string;
  /**
   * State of the destination shipping address of the shipment. Required by some couriers.
   */
  tracking_state?: string;
  /**
   * Slug group is a group of slugs which belong to same courier. For example, when you inpit &#34;fedex-group&#34; as slug_group, AfterShip will detect the tracking with &#34;fedex-uk&#34;, &#34;fedex-fims&#34;, and other slugs which belong to &#34;fedex&#34;. It cannot be used with slug at the same time. (
   */
  slug_group?: SlugGroupV1;
  /**
   * Enter .
   */
  origin_country_region?: string;
  /**
   * Enter .
   */
  destination_country_region?: string;
}
