/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { DetectCourierResponseData } from "./DetectCourierResponseData";

/**
 *
 */
export interface DetectCourierResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: DetectCourierResponseData;
}
