/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Courier } from "./Courier";

export interface DetectCourierResponse {
  /**
   * Total count of courier objects
   */
  total?: number;
  /**
   * Array of  object.
   */
  couriers?: Courier[];
}
