/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { OrderProcessingTimeEstimatedPickupPredictRequest } from "./OrderProcessingTimeEstimatedPickupPredictRequest";

export interface EstimatedPickupPredictRequest {
  /**
   * The local order time in the origin address time zone of the package.
   */
  order_time: string;
  /**
   * Order cut off time in the origin address time zone. The default value set by AfterShip is 18:00:00.
   */
  order_cutoff_time?: string;
  /**
   * Operating days in a week. Number refers to the weekday.E.g., [1,2,3,4,5] means operating days are from Monday to Friday.AfterShip will set [1,2,3,4,5] as the default value.
   */
  business_days?: number[];
  /**
   *
   */
  order_processing_time?: OrderProcessingTimeEstimatedPickupPredictRequest;
}
