/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * AfterShip uses this object to calculate the total weight of the order.
 */
export interface EstimatedDeliveryDateResponseWeight {
  /**
   * The weight unit of the package.
   */
  unit: string;
  /**
   * The weight of the shipment.
   */
  value: number;
}
