/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { EstimatedDeliveryDateRequestDestinationAddress } from "./EstimatedDeliveryDateRequestDestinationAddress";
import { EstimatedDeliveryDateRequestWeight } from "./EstimatedDeliveryDateRequestWeight";
import { EstimatedDeliveryDateRequestEstimatedPickup } from "./EstimatedDeliveryDateRequestEstimatedPickup";
import { EstimatedDeliveryDateRequestOriginAddress } from "./EstimatedDeliveryDateRequestOriginAddress";

/**
 *
 */
export interface EstimatedDeliveryDateRequest {
  /**
   * AfterShip&#39;s unique code of courier. Please refer to https://track.aftership.com/couriers/download.
   */
  slug: string;
  /**
   * AfterShip’s unique code represents carrier’s shipping and delivery options. Refer to .
   */
  service_type_name?: string | null;
  /**
   * The location from where the package is picked up by the carrier to be delivered to the final destination.
   */
  origin_address: EstimatedDeliveryDateRequestOriginAddress;
  /**
   * The final destination of the customer where the delivery will be made.
   */
  destination_address: EstimatedDeliveryDateRequestDestinationAddress;
  /**
   * AfterShip uses this object to calculate the total weight of the order.
   */
  weight?: EstimatedDeliveryDateRequestWeight | null;
  /**
   * The number of packages.
   */
  package_count?: number | null;
  /**
   * The local pickup time in the origin address time zone of the package.Either `pickup_time` or `estimated_pickup` is required.
   */
  pickup_time?: string | null;
  /**
   * The local pickup time of the package.Either `pickup_time` or `estimated_pickup` is required.
   */
  estimated_pickup?: EstimatedDeliveryDateRequestEstimatedPickup | null;
}
