/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { ReasonEventsCheckpoint } from "./ReasonEventsCheckpoint";

export interface EventsCheckpoint {
    /**
     * Represents the event code.
     */
    code?: string;
    /**
     * Describes the specific reason that led to the event.
     */
    reason?: ReasonEventsCheckpoint;
}

