/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PaginationGetCourierConnectionsResponse } from "./PaginationGetCourierConnectionsResponse";
import { CourierConnection } from "./CourierConnection";

export interface GetCourierConnectionsResponse {
    /**
     * 
     */
    pagination: Pagination;
}

