/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
export interface GetCourierConnectionsQuery {
  courier_slug?: string;
  cursor?: string;
  limit?: string;
}
