/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { CourierConnection } from "./CourierConnection";
import { Pagination } from "./Pagination";

export interface GetCourierConnectionsResponse {
  /**
   *
   */
  pagination: Pagination;
  /**
   *
   */
  courier_connections?: CourierConnection[];
}
