/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TagV1 } from "./TagV1";
import { Checkpoint } from "./Checkpoint";

export interface GetCheckpointBySlugTrackingNumberResponse {
    /**
     * Tracking id
     */
    id?: string;
    /**
     * Tracking number.
     */
    tracking_number?: string;
    /**
     * Unique code of courier.
     */
    slug?: string;
    /**
     * Current status of tracking. (
     */
    tag?: TagV1;
    /**
     * Current subtag of tracking. (
     */
    subtag?: string;
    /**
     * Normalized tracking message. (
     */
    subtag_message?: string;
    /**
     * Object describes checkpoint information.
     */
    checkpoint?: Checkpoint;
}

