/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { GetCourierConnectionsResponseDataPagination } from "./GetCourierConnectionsResponseDataPagination";
import { CourierConnection } from "./CourierConnection";

/**
 *
 */
export interface GetCourierConnectionsResponseData {
  /**
   *
   */
  pagination?: GetCourierConnectionsResponseDataPagination;
  /**
   *
   */
  courier_connections?: CourierConnection[];
}
