/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
export interface GetCheckpointBySlugTrackingNumberQuery {
    fields?: string;
    lang?: string;
    tracking_account_number?: string;
    tracking_origin_country?: string;
    tracking_destination_country?: string;
    tracking_key?: string;
    tracking_postal_code?: string;
    tracking_ship_date?: string;
    tracking_state?: string;
}

