/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { GetCouriersResponseData } from "./GetCouriersResponseData";

/**
 *
 */
export interface GetCouriersResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: GetCouriersResponseData;
}
