/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { GetCourierConnectionsResponseData } from "./GetCourierConnectionsResponseData";

/**
 *
 */
export interface GetCourierConnectionsResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: GetCourierConnectionsResponseData;
}
