/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { CourierConnection } from "./CourierConnection";

/**
 * This model represents user-created courier connection details. AfterShip will use this information to retrieve tracking updates from carriers based on the provided tracking numbers.
 */
export interface GetCourierConnectionsByIdResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: CourierConnection;
}
