/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { PaginationGetTrackingsResponse } from "./PaginationGetTrackingsResponse";
import { Tracking } from "./Tracking";

export interface GetTrackingsResponse {
    /**
     * 
     */
    pagination: Pagination;
}

