/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { GetTrackingsResponseData } from "./GetTrackingsResponseData";

/**
 *
 */
export interface GetTrackingsResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: GetTrackingsResponseData;
}
