/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { GetTrackingsResponseDataPagination } from "./GetTrackingsResponseDataPagination";
import { Tracking } from "./Tracking";

/**
 *
 */
export interface GetTrackingsResponseData {
  /**
   * The Pagination holds the information for the pagination when the response contains multiple objects.
   */
  pagination?: GetTrackingsResponseDataPagination;
  /**
   * Array of
   */
  trackings?: Tracking[];
}
