/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Tracking } from "./Tracking";
import { Pagination } from "./Pagination";

export interface GetTrackingsResponse {
  /**
   *
   */
  pagination: Pagination;
  /**
   * Array of
   */
  trackings?: Tracking[];
}
