/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface MetaV1 {
  /**
   * meta code
   */
  code: number;
  /**
   * error message, only exist if the response status is not 2xx
   */
  message?: string;
  /**
   * error type, only exist if the response status is not 2xx
   */
  type?: string;
}
