/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * error type, only exist if the response status is not 2xx
 */
export enum MetaType {
  "BadRequest" = "BadRequest",
  "Unauthorized" = "Unauthorized",
  "Forbidden" = "Forbidden",
  "NotFound" = "NotFound",
  "TooManyRequests" = "TooManyRequests",
  "InternalError" = "InternalError",
}
