/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface NextCouriersMarkTrackingCompletedByIdResponse {
    /**
     * Unique code of courier. Get courier 
     */
    slug: string;
    /**
     * Tracking number.
     */
    tracking_number: string;
    /**
     * Source of next couriers.
     */
    source?: string;
    /**
     * The field contains the official tracking URL of the next courier, if available. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the data related to the destination country/region and the shipment&#39;s language is unavailable, AfterShip will default the language parameter of the link to &#34;US&#34;.
     */
    courier_tracking_link?: string;
    /**
     * The field provides the link for modifying delivery instructions (such as delivery date and shipping address) if supported by the next carrier. The language parameter of this link is determined by the destination country/region and the language associated with the shipment. If the data related to the destination country/region and the shipment&#39;s language is unavailable, AfterShip will default the language parameter of the link to &#34;US&#34;.
     */
    courier_redirect_link?: string;
}

