/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface NextCouriersRetrackTrackingByIdResponse {
    /**
     * Unique code of courier. Get courier 
     */
    slug: string;
    /**
     * Tracking number.
     */
    tracking_number: string;
    /**
     * Source of next couriers.
     */
    source?: string;
}

