/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface Notification {
    /**
     * Email address(es) to receive email notifications.
     */
    emails?: string[];
    /**
     * The phone number(s) to receive sms notifications. 
     */
    smses?: string[];
}

