/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface NotificationRequestV1 {
    /**
     * Email address(es) to receive email notifications.Accept either array or comma separated as input.
     */
    emails?: string[];
    /**
     * The phone number(s) to receive sms notifications.  Enter `+` and `area code` before phone number.Accept either array or comma separated as input.
     */
    smses?: string[];
}

