/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { DataNotificationResponseV1 } from "./DataNotificationResponseV1";

export interface NotificationResponseV1 {
    /**
     * Meta data
     */
    meta?: MetaV1;
    /**
     * 
     */
    data?: DataNotificationResponseV1;
}

