/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface OrderProcessingTimeEstimatedPickupPredictRequest {
  /**
   * Processing time of an order, from being placed to being picked up. Only support day as value now.AfterShip will set day as the default value.
   */
  unit?: string;
  /**
   * Processing time of an order, from being placed to being picked up.AfterShip will set 0 as the default value.
   */
  value?: number;
}
