/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface PaginationGetTrackingsResponse {
    /**
     * The total number of trackings.
     */
    total?: number;
    /**
     * A string representing the cursor value for the next page of results.
     */
    next_cursor?: string;
    /**
     * To indicate if next page is available.
     */
    has_next_page?: boolean;
}

