/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
export interface Pagination {
    total: number;
    page: number;
    limit: number;
    has_next_page: boolean | null;
}