/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface PostCourierConnectionsRequest {
    /**
     * Unique code of courier. Get the slugs from .
     */
    courier_slug: string;
    /**
     * It refers to the authentication details required for each specific carrier details required for each specific carrier (such as API keys, username, password, etc.) that the user must provide to establish a carrier connection. The content varies by carrier.
     */
    credentials: {[key: string]: any};
}

