/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Estimateddeliverydate } from "./Estimateddeliverydate";

export interface PredictBatchRequest {
    /**
     * 
     */
    estimated_delivery_dates: Estimateddeliverydate[];
}

