/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { EstimatedDeliveryDateResponse } from "./EstimatedDeliveryDateResponse";

export interface PredictBatchResponse {
    /**
     * 
     */
    estimated_delivery_dates: EstimatedDeliveryDateResponse[];
}

