/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { EstimatedDeliveryDateRequest } from "./EstimatedDeliveryDateRequest";

export interface PredictBatchRequest {
  /**
   *
   */
  estimated_delivery_dates: EstimatedDeliveryDateRequest[];
}
