/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { EstimatedDeliveryDateResponse } from "./EstimatedDeliveryDateResponse";

/**
 *
 */
export interface PredictResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: EstimatedDeliveryDateResponse;
}
