/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Estimateddeliverydate2 } from "./Estimateddeliverydate2";

export interface PredictBatchResponse {
    /**
     * 
     */
    estimated_delivery_dates: Estimateddeliverydate2[];
}

