/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

import { PredictBatchResponseData } from "./PredictBatchResponseData";

/**
 *
 */
export interface PredictBatchResponse {
  /**
   * The response headers.
   */
  response_headers: Record<string, string>;

  /**
   * The response data.
   */
  data: PredictBatchResponseData;
}
