/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface ReasonEventsCheckpoint {
  /**
   * The code of the reason.
   */
  code?: string;
}
