/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface ShipmentWeightTracking {
  /**
   * The unit in which the value field is expressed.
   */
  unit?: string;
  /**
   * The total amount of shipment weight.
   */
  value?: number;
}
