/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Slug group is a group of slugs which belong to same courier. For example, when you inpit &#34;fedex-group&#34; as slug_group, AfterShip will detect the tracking with &#34;fedex-uk&#34;, &#34;fedex-fims&#34;, and other slugs which belong to &#34;fedex&#34;. It cannot be used with slug at the same time. (
 */
export enum SlugGroup {
  "amazon-group" = "amazon-group",
  "fedex-group" = "fedex-group",
  "toll-group" = "toll-group",
  "taqbin-group" = "taqbin-group",
  "tnt-group" = "tnt-group",
  "cj-group" = "cj-group",
  "hermes-group" = "hermes-group",
  "dpd-group" = "dpd-group",
  "gls-group" = "gls-group",
  "dhl-group" = "dhl-group",
  "fastway-group" = "fastway-group",
  "asendia-group" = "asendia-group",
}
