/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Current status of tracking. (
 */
export enum Tag {
  "Pending" = "Pending",
  "InfoReceived" = "InfoReceived",
  "InTransit" = "InTransit",
  "OutForDelivery" = "OutForDelivery",
  "AttemptFail" = "AttemptFail",
  "Delivered" = "Delivered",
  "AvailableForPickup" = "AvailableForPickup",
  "Exception" = "Exception",
  "Expired" = "Expired",
}
