/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The field indicates the source of last-mile carrier.
 */
export enum TrackingLastMileSource {
  "system" = "system",
  "user" = "user",
}
