/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { DataTrackingResponseForGetTrackings } from "./DataTrackingResponseForGetTrackings";

export interface TrackingResponseForGetTrackings {
    /**
     * Meta data
     */
    meta: Meta;
    /**
     * 
     */
    data?: DataTrackingResponseForGetTrackings;
}

