/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { DataTrackingResponseGetMultipleV1 } from "./DataTrackingResponseGetMultipleV1";

export interface TrackingResponseGetMultipleV1 {
  /**
   * Meta data
   */
  meta: MetaV1;
  /**
   *
   */
  data?: DataTrackingResponseGetMultipleV1;
}
