/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The original outbound shipment linked to this return. Use this to trace a return back to its source delivery.This field is only present when `shipment_direction = &#34;return&#34;` and AfterShip has detected a linked forward shipment.
 */
export interface TrackingForwardShipment {
  /**
   * AfterShip system-assigned unique identifier of the linked outbound shipment.
   */
  id?: string;
}
