/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingCustomEstimatedDeliveryDateType } from "./TrackingCustomEstimatedDeliveryDateType";

/**
 * Estimated delivery time of the shipment based on your . It uses the format `YYYY-MM-DD` based on the shipment recipient’s timezone.
 */
export interface TrackingCustomEstimatedDeliveryDate {
  /**
   * The format of the EDD. Either a single date or a date range.
   */
  type?: TrackingCustomEstimatedDeliveryDateType;
  /**
   * The specific EDD date.
   */
  datetime?: string | null;
  /**
   * For a date range EDD format, the date for the lower end of the range.
   */
  datetime_min?: string | null;
  /**
   * For a date range EDD format, the date for the upper end of the range.
   */
  datetime_max?: string | null;
}
