/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Physical dimensions of the package (length, width and height).
 */
export interface TrackingShipmentDimensions {
  /**
   * The unit in which the dimension values are expressed. Allowed values: cm, in
   */
  unit?: string;
  /**
   * The length of the shipment package.
   */
  length?: number;
  /**
   * The width of the shipment package.
   */
  width?: number;
  /**
   * The height of the shipment package.
   */
  height?: number;
}
