/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { Tracking } from "./Tracking";

export interface TrackingResponseV1 {
  /**
   * Meta data
   */
  meta: MetaV1;
  /**
   * Object describes the tracking information.&lt;div style=&#34;display:none; height: 0&#34;&gt;&lt;/div&gt;
   */
  data: Tracking;
}
