/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The format of the EDD. Either a single date or a date range.
 */
export enum TrackingCustomEstimatedDeliveryDateType {
  range = "range",
  specific = "specific",
}
