/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingMultiPieceInfoPiecesType } from "./TrackingMultiPieceInfoPiecesType";

/**
 *
 */
export interface TrackingMultiPieceInfoPieces {
  /**
   * AfterShip system-assigned unique identifier for the piece.
   */
  tracking_id?: string;
  /**
   * Carrier-assigned tracking number for the piece.
   */
  tracking_number?: string;
  /**
   * Type of the piece within the MPS: `master` or `child`.
   */
  type?: TrackingMultiPieceInfoPiecesType;
  /**
   * Indicates whether the tracking number can be used to retrieve tracking updates on the carrier&#39;s side. If not, it means the carrier can only return a child tracking number, but cannot independently provide tracking updates for the sub-shipment. In this case, it is not recommended for you to import this tracking number into AfterShip for tracking.
   */
  trackable?: boolean;
}
