/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { TrackingResponseForGetTrackingsData } from "./TrackingResponseForGetTrackingsData";

/**
 * Tracking response for getting tracking
 */
export interface TrackingResponseForGetTrackings {
  /**
   * Meta data
   */
  meta: Meta;
  /**
   *
   */
  data?: TrackingResponseForGetTrackingsData;
}
