/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingFirstEstimatedDeliveryType } from "./TrackingFirstEstimatedDeliveryType";
import { TrackingFirstEstimatedDeliverySource } from "./TrackingFirstEstimatedDeliverySource";

/**
 * The shipment’s original estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
 */
export interface TrackingFirstEstimatedDelivery {
  /**
   * The format of the EDD. Either a single date or a date range.
   */
  type?: TrackingFirstEstimatedDeliveryType;
  /**
   * The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
   */
  source?: TrackingFirstEstimatedDeliverySource;
  /**
   * The latest EDD time.
   */
  datetime?: string | null;
  /**
   * For a date range EDD format, the date and time for the lower end of the range.
   */
  datetime_min?: string | null;
  /**
   * For a date range EDD format, the date and time for the upper end of the range.
   */
  datetime_max?: string | null;
}
