/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
 */
export enum TrackingLatestEstimatedDeliverySource {
  "Carrier EDD" = "Carrier EDD",
  "AfterShip EDD" = "AfterShip EDD",
  "Custom EDD" = "Custom EDD",
  "Order EDD" = "Order EDD",
}
