/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Type of the piece within the MPS: `master` or `child`.
 */
export enum TrackingMultiPieceInfoPiecesType {
  master = "master",
  child = "child",
}
