/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingLatestEstimatedDeliveryType } from "./TrackingLatestEstimatedDeliveryType";
import { TrackingLatestEstimatedDeliverySource } from "./TrackingLatestEstimatedDeliverySource";

/**
 * The most recently calculated estimated delivery date. It could be provided by the carrier, AfterShip AI, or based on your custom settings. The format of carrier EDDs may differ depending on how the carrier provides it:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ AfterShip AI and custom EDDs always use the format `YYYY-MM-DD`. All EDDs use the shipment recipient’s timezone.
 */
export interface TrackingLatestEstimatedDelivery {
  /**
   * The format of the EDD. Either a single date or a date range.
   */
  type?: TrackingLatestEstimatedDeliveryType;
  /**
   * The source of the EDD. Either the carrier, AfterShip AI, or based on your custom EDD settings.
   */
  source?: TrackingLatestEstimatedDeliverySource;
  /**
   * The latest EDD time.
   */
  datetime?: string | null;
  /**
   * For a date range EDD format, the date and time for the lower end of the range.
   */
  datetime_min?: string | null;
  /**
   * For a date range EDD format, the date and time for the upper end of the range.
   */
  datetime_max?: string | null;
  /**
   * Explains the reason for a change to the latest_estimated_delivery. This string will only have a value if:1. The source for the latest EDD is AfterShip EDD. 2. The reason for the change is known.For a comprehensive list of reasons, please refer to .
   */
  revise_reason?: string | null;
}
