/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { DataTrackingDeleteResponseV1 } from "./DataTrackingDeleteResponseV1";

export interface TrackingDeleteResponseV1 {
    /**
     * Meta data
     */
    meta: MetaV1;
    /**
     * 
     */
    data: DataTrackingDeleteResponseV1;
}

