/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The model contains the total amount of carbon emissions generated by the shipment. - AfterShip will provide this data only when it is available, and its availability is contingent upon the location and weight information that AfterShip can obtain.- The values will be accessible solely for shipments that have been successfully delivered. However, in the event of a shipping update after the delivery status has been achieved, the value may change.- It’s a paid service and only for Tracking Enterprise users, please contact your customer success manager if you want to know more.
 */
export interface TrackingCarbonEmissions {
  /**
   * The unit in which the value field is expressed. Allowed values: kg
   */
  unit?: string;
  /**
   * The total amount of carbon emissions
   */
  value?: number;
}
