/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { MetaV1 } from "./MetaV1";
import { DataTrackingResponseV1 } from "./DataTrackingResponseV1";

export interface TrackingResponseV1 {
    /**
     * Meta data
     */
    meta: MetaV1;
    /**
     * 
     */
    data: DataTrackingResponseV1;
}

