/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingResponseForGetTrackingsDataPagination } from "./TrackingResponseForGetTrackingsDataPagination";
import { Tracking } from "./Tracking";

/**
 *
 */
export interface TrackingResponseForGetTrackingsData {
  /**
   * The Pagination holds the information for the pagination when the response contains multiple objects.
   */
  pagination?: TrackingResponseForGetTrackingsDataPagination;
  /**
   * Array of
   */
  trackings?: Tracking[];
}
