/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { TrackingMultiPieceInfoType } from "./TrackingMultiPieceInfoType";
import { TrackingMultiPieceInfoPieces } from "./TrackingMultiPieceInfoPieces";

/**
 * Multi-piece shipment refers to a scenario where a single shipment order is fulfilled by multiple physical packages. Each piece has its own carrier-assigned tracking number, but all pieces belong to the same shipment. This commonly occurs when an order is too large to fit in one box, or when items are packed separately for handling reasons.This field contains multi-piece shipment metadata describing a group of packages that belong to the same shipment.This field returns a value only when your subscription plan includes a multi-piece feature. To enable, go to .
 */
export interface TrackingMultiPieceInfo {
  /**
   * Indicates the role of the current tracking object within the multi-piece shipment.Possible values:- `master`: The main tracking number representing the entire shipment. It may not always exist.- `child`: A sub-tracking number belonging to one of the pieces in the shipment.
   */
  type?: TrackingMultiPieceInfoType;
  /**
   * List of all pieces in the MPS, including the master and all child pieces.
   */
  pieces?: TrackingMultiPieceInfoPieces[];
}
