/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Meta } from "./Meta";
import { Tracking } from "./Tracking";

export interface TrackingResponse {
  /**
   * Meta data
   */
  meta: Meta;
  /**
   * Object describes the tracking information.&lt;div style=&#34;display:none; height: 0&#34;&gt;&lt;/div&gt;
   */
  data: Tracking;
}
