/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 *
 */
export interface TrackingProofOfDelivery {
  /**
   * The file type of the proof of delivery record. Currently, only images are supported.
   */
  type?: string;
  /**
   * The URL of the proof of delivery record.
   */
  url?: string;
}
