/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * The promised delivery date of the order in shipment recipient’s timezone.
 */
export interface UpdateTrackingByIdRequestOrderPromisedDeliveryDate {
  /**
   * The promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
   */
  promised_delivery_date?: string | null;
  /**
   * Earliest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
   */
  promised_delivery_date_min?: string | null;
  /**
   * Latest promised delivery date of the order. It uses the formats:- YYYY-MM-DD- YYYY-MM-DDTHH:mm:ss- YYYY-MM-DDTHH:mm:ssZ
   */
  promised_delivery_date_max?: string | null;
}
