/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

/**
 * Shipment delivery type- `pickup_at_store`- `pickup_at_courier`- `door_to_door`
 */
export enum UpdateTrackingByIdRequestDeliveryType {
  pickup_at_store = "pickup_at_store",
  pickup_at_courier = "pickup_at_courier",
  door_to_door = "door_to_door",
}
