/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */

export interface WeightEstimateddeliverydate2 {
    /**
     * The weight unit of the package. 
     */
    unit: string;
    /**
     * The weight of the shipment.
     */
    value: number;
}

