/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Request } from "../lib/request";
import { AftershipError, AfterShipErrorCodes } from "../error";
import { GetCourierConnectionsResponse } from "../model/GetCourierConnectionsResponse";
import { GetCourierConnectionsQuery } from "../model/GetCourierConnectionsQuery";
import { PostCourierConnectionsRequest } from "../model/PostCourierConnectionsRequest";
import { PostCourierConnectionsResponse } from "../model/PostCourierConnectionsResponse";
import { GetCourierConnectionsByIdResponse } from "../model/GetCourierConnectionsByIdResponse";
import { PutCourierConnectionsByIdRequest } from "../model/PutCourierConnectionsByIdRequest";
import { PutCourierConnectionsByIdResponse } from "../model/PutCourierConnectionsByIdResponse";
import { DeleteCourierConnectionsByIdResponse } from "../model/DeleteCourierConnectionsByIdResponse";

export class CourierConnectionApi {
  private readonly request: Request;

  constructor(request: Request) {
    this.request = request;
  }

  /**
   * Get courier connection results of multiple courier connections.
   */
  public async getCourierConnections(
    query?: GetCourierConnectionsQuery,
    headers?: { [key: string]: any },
  ): Promise<GetCourierConnectionsResponse> {
    const url = `/tracking/2026-01/courier-connections`;
    return this.request.makeRequest<GetCourierConnectionsResponse>({
      url: url,
      method: "GET",
      query,
      headers,
    });
  }
  /**
   *
   */
  public async postCourierConnections(
    body: PostCourierConnectionsRequest,
    headers?: { [key: string]: any },
  ): Promise<PostCourierConnectionsResponse> {
    const url = `/tracking/2026-01/courier-connections`;
    return this.request.makeRequest<PostCourierConnectionsResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
  /**
   * Get courier connection results of a single courier connection.
   */
  public async getCourierConnectionsById(
    id: string,
    headers?: { [key: string]: any },
  ): Promise<GetCourierConnectionsByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2026-01/courier-connections/${id}`;
    return this.request.makeRequest<GetCourierConnectionsByIdResponse>({
      url: url,
      method: "GET",
      headers,
    });
  }
  /**
   * Update a courier connection.
   */
  public async putCourierConnectionsById(
    id: string,
    body: PutCourierConnectionsByIdRequest,
    headers?: { [key: string]: any },
  ): Promise<PutCourierConnectionsByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2026-01/courier-connections/${id}`;
    return this.request.makeRequest<PutCourierConnectionsByIdResponse>({
      url: url,
      method: "PATCH",
      body,
      headers,
    });
  }
  /**
   * Delete a courier connection.
   */
  public async deleteCourierConnectionsById(
    id: string,
    headers?: { [key: string]: any },
  ): Promise<DeleteCourierConnectionsByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2026-01/courier-connections/${id}`;
    return this.request.makeRequest<DeleteCourierConnectionsByIdResponse>({
      url: url,
      method: "DELETE",
      headers,
    });
  }
}
