/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Request } from "../lib/request";
import { AftershipError, AfterShipErrorCodes } from "../error";
import { DetectCourierRequest } from "../model/DetectCourierRequest";
import { DetectCourierResponse } from "../model/DetectCourierResponse";
import { GetCouriersResponse } from "../model/GetCouriersResponse";
import { GetCouriersQuery } from "../model/GetCouriersQuery";

export class CourierApi {
  private readonly request: Request;

  constructor(request: Request) {
    this.request = request;
  }

  /**
   * Return a list of couriers.
   */
  public async getCouriers(
    query?: GetCouriersQuery,
    headers?: { [key: string]: any },
  ): Promise<GetCouriersResponse> {
    const url = `/tracking/2026-01/couriers`;
    return this.request.makeRequest<GetCouriersResponse>({
      url: url,
      method: "GET",
      query,
      headers,
    });
  }
  /**
   * Return a list of matched couriers based on tracking number format and  or a list of couriers.
   */
  public async detectCourier(
    body: DetectCourierRequest,
    headers?: { [key: string]: any },
  ): Promise<DetectCourierResponse> {
    const url = `/tracking/2026-01/couriers/detect`;
    return this.request.makeRequest<DetectCourierResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
}
