/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Request } from "../lib/request";
import { AftershipError, AfterShipErrorCodes } from "../error";
import { EstimatedDeliveryDateRequest } from "../model/EstimatedDeliveryDateRequest";
import { PredictResponse } from "../model/PredictResponse";
import { PredictBatchRequest } from "../model/PredictBatchRequest";
import { PredictBatchResponse } from "../model/PredictBatchResponse";

export class EstimatedDeliveryDateApi {
  private readonly request: Request;

  constructor(request: Request) {
    this.request = request;
  }

  /**
   * &gt; The estimated delivery date is provided by AfterShip, based on its AI-predictive model. You can display the EDD on the product page, cart, and order checkout page. It indicates when a customer will receive the order.You can use  to activate this feature.
   */
  public async predict(
    body: EstimatedDeliveryDateRequest,
    headers?: { [key: string]: any },
  ): Promise<PredictResponse> {
    const url = `/tracking/2026-01/estimated-delivery-date/predict`;
    return this.request.makeRequest<PredictResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
  /**
   * &gt; The estimated delivery date is provided by AfterShip, based on its AI-predictive model. You can display the EDD on the product page, cart, and order checkout page. It indicates when a customer will receive the order.You can use  to activate this feature.Supported functionalities require:1. One `EstimatedDeliveryDate` object for one prediction result.2. Maximum 5 `EstimatedDeliveryDate` objects are allowed.3. API call will fail if any of the requests `EstimatedDeliveryDate` objects do not meet the specification requirement.
   */
  public async predictBatch(
    body: PredictBatchRequest,
    headers?: { [key: string]: any },
  ): Promise<PredictBatchResponse> {
    const url = `/tracking/2026-01/estimated-delivery-date/predict-batch`;
    return this.request.makeRequest<PredictBatchResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
}
