/*
 * This code was auto generated by AfterShip SDK Generator.
 * Do not edit the class manually.
 */
import { Request } from "../lib/request";
import { AftershipError, AfterShipErrorCodes } from "../error";
import { GetTrackingsQuery } from "../model/GetTrackingsQuery";
import { CreateTrackingRequest } from "../model/CreateTrackingRequest";
import { UpdateTrackingByIdRequest } from "../model/UpdateTrackingByIdRequest";
import { RetrackTrackingByIdResponse } from "../model/RetrackTrackingByIdResponse";
import { MarkTrackingCompletedByIdRequest } from "../model/MarkTrackingCompletedByIdRequest";
import { MarkTrackingCompletedByIdResponse } from "../model/MarkTrackingCompletedByIdResponse";
import { GetTrackingsResponse } from "../model/GetTrackingsResponse";
import { CreateTrackingResponse } from "../model/CreateTrackingResponse";
import { GetTrackingByIdResponse } from "../model/GetTrackingByIdResponse";
import { GetTrackingByIdQuery } from "../model/GetTrackingByIdQuery";
import { UpdateTrackingByIdResponse } from "../model/UpdateTrackingByIdResponse";
import { DeleteTrackingByIdResponse } from "../model/DeleteTrackingByIdResponse";

export class TrackingApi {
  private readonly request: Request;

  constructor(request: Request) {
    this.request = request;
  }

  /**
   * Get tracking results of multiple trackings.&lt;div style=&#34;visibility:hidden; height: 0&#34;&gt;&lt;/div&gt;
   */
  public async getTrackings(
    query?: GetTrackingsQuery,
    headers?: { [key: string]: any },
  ): Promise<GetTrackingsResponse> {
    const url = `/tracking/2025-07/trackings`;
    return this.request.makeRequest<GetTrackingsResponse>({
      url: url,
      method: "GET",
      query,
      headers,
    });
  }
  /**
   * Create a tracking.&lt;div style=&#34;visibility:hidden; height: 0&#34;&gt;&lt;/div&gt;
   */
  public async createTracking(
    body: CreateTrackingRequest,
    headers?: { [key: string]: any },
  ): Promise<CreateTrackingResponse> {
    const url = `/tracking/2025-07/trackings`;
    return this.request.makeRequest<CreateTrackingResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
  /**
   * Get tracking results of a single tracking.
   */
  public async getTrackingById(
    id: string,
    query?: GetTrackingByIdQuery,
    headers?: { [key: string]: any },
  ): Promise<GetTrackingByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2025-07/trackings/${id}`;
    return this.request.makeRequest<GetTrackingByIdResponse>({
      url: url,
      method: "GET",
      query,
      headers,
    });
  }
  /**
   * Update a tracking.
   */
  public async updateTrackingById(
    id: string,
    body: UpdateTrackingByIdRequest,
    headers?: { [key: string]: any },
  ): Promise<UpdateTrackingByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2025-07/trackings/${id}`;
    return this.request.makeRequest<UpdateTrackingByIdResponse>({
      url: url,
      method: "PUT",
      body,
      headers,
    });
  }
  /**
   * Delete a tracking.
   */
  public async deleteTrackingById(
    id: string,
    headers?: { [key: string]: any },
  ): Promise<DeleteTrackingByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2025-07/trackings/${id}`;
    return this.request.makeRequest<DeleteTrackingByIdResponse>({
      url: url,
      method: "DELETE",
      headers,
    });
  }
  /**
   * Retrack an expired tracking. Max 3 times per tracking.
   */
  public async retrackTrackingById(
    id: string,
    headers?: { [key: string]: any },
  ): Promise<RetrackTrackingByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2025-07/trackings/${id}/retrack`;
    return this.request.makeRequest<RetrackTrackingByIdResponse>({
      url: url,
      method: "POST",
      headers,
    });
  }
  /**
   * Mark a tracking as completed. The tracking won&#39;t auto update until retrack it.
   */
  public async markTrackingCompletedById(
    id: string,
    body: MarkTrackingCompletedByIdRequest,
    headers?: { [key: string]: any },
  ): Promise<MarkTrackingCompletedByIdResponse> {
    if (!id) {
      throw new AftershipError(
        "Invalid params: id",
        AfterShipErrorCodes.BAD_REQUEST,
      );
    }
    const url = `/tracking/2025-07/trackings/${id}/mark-as-completed`;
    return this.request.makeRequest<MarkTrackingCompletedByIdResponse>({
      url: url,
      method: "POST",
      body,
      headers,
    });
  }
}
